<?php
/**
* @author justin (with e)
* @copyright 2019
*/
ini_set('max_execution_time', 0);
ini_set("memory_limit", "2G");

require_once(APPPATH."constants.php");
$CI =& get_instance();
$CI->load->model('extras');
$CI->load->library('PdfCreator_mpdf');

$mpdf = new mPDF('utf-8','LETTER-L','9','','10','10','35','10','5','5');
                                                                                                                                                                                                                                                                                                                                                                                                       
$header = "
<table class='header' width='100%' style='padding:0;'>
	<tr>
		<td rowspan='3' style='text-align: left;' width='60px'><img src='images/school_logo.jpg' style='width: 60px;text-align: center;' /></td>
		<td>&nbsp;</td>
	</tr>

	<tr>
		<td valign='middle' width='90%' style='font-size: 20px;'><b>Pinnacle Technologies Inc.</b></span></td>
	</tr>

	<tr>
		<td style='border-bottom: 1px solid #000;' width='90%'>Human Resources Department</td>
	</tr>

	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>

	<tr>
		<td></td>
		<td valign='middle' style='text-align: center;'><strong>Leave Report</strong></span></td>
	</tr>

	<tr>
		<td></td>
		<td valign='middle' style='text-align: center;'><strong>Attendance  Cut Off: ".date("F j, Y", strtotime($dfrom))." to ".date("F j, Y", strtotime($dto))."</strong></span></td>
	</tr>
</table>
";

$footer = "
<table width='100%'>
	<tr>
		<td width='50%' style='border-top: 1px solid #000'>
			<strong>". $userdata["user"] ."</strong>
		</td>
		<td width='50%' style='text-align: right; border-top: 1px solid #000'>
			<strong>". date("F m, Y") ." -</strong> Page  <strong>{PAGENO}</strong> of <strong>{nbpg}</strong>
		</td>
	</tr>
</table>
";

$mpdf->SetHTMLHeader($header);
$mpdf->SetHTMLFooter($footer);

$style = '
<style>
	.table-striped tr:nth-child(even) {background: #CCC}
	.table-striped tr:nth-child(odd) {background: #FFF}
	.container{
		content: "";
		display: block;
		clear: both;
	}
	table{
		border-collapse: collapse;
		font-family:calibri;
	}
	table td{
		padding: 0 5px;
	}
	th {
		padding: 10px 5px;
	}

	.center{
		text-align: center;
	}

	.table-striped tr td.header{
		padding: 5px;
	}
</style>
';

$content = $style;

$content .= '
<div class="container">
	<table class="table table-striped" cellspacing="10" border="1" width="100%">
		<thead>
			<tr>
				<th width="20%">EMPLOYEE NAME</th>
				<th width="14%">POSITION</th>
				<th width="8%">DEPARTMENT</th>
				<th width="8%">TYPE</th>
				<th width="8%">DAYS</th>
				<th width="18%">DATE OF EXCLUSIVE</th>
				<th width="16%">REASON</th>
				<th width="8%">REMAINING BALANCE</th>
			</tr>
		</thead>
		<tbody>
';

foreach (array("teaching" => "Teaching", "nonteaching" => "Non-Teaching") as $teaching_type => $teaching_desc):
	if(isset($list[$teaching_type]) && count($list[$teaching_type])){
		$content .='
			<tr>
				<td colspan="8" class="header">
					<strong>'. $teaching_desc .'</strong>
				</td>
			</tr>
		';

		foreach ($list[$teaching_type] as $key => $info) {
			$content .='
			<tr>
				<td>'. $info["name"] .'</td>
				<td class="center">'. $info["position"] .'</td>
				<td class="center">'. $info["department"] .'</td>
				<td class="center">'. ($info["type"] == "ABSENT" ? "LEAVE W/OUT PAY" : $info["type"]) .'</td>
				<td class="center">'. $info["days"] .'</td>
				<td class="center">'. $info["date_exclusive"] .'</td>
				<td>'. $info["reason"] .'</td>
				<td class="center">'. $info["balance"] .'</td>
			</tr>
			';
		}
	}
endforeach;

if(!count($list)):
	$content .='
			<tr>
				<td colspan="8" class="center">
					<strong>No Data Available.</strong>
				</td>
			</tr>
	';
endif;
$content .='			
		</tbody>
	</table>
</div>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;<b>Generated by:</b>
<br><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u><strong>'. $user_data["user"] .'</strong></u><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;Position
<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;<b>Noted by:</b>
<br>
<br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;<u><strong>'. $user_data["hr"] .'</strong></u><br>
&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;HR Director
';

// $content = mb_convert_encoding($content, 'UTF-8', 'UTF-8');
$mpdf->WriteHTML($content);
$mpdf->Output();